version: '3.1'

services:
  php:
    container_name: survey_php
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - ${HTTP_PORT}:80
    restart: always
    volumes:
      - ./server/www:/var/www/html/
      - ./R:/var/R
      - ./scalepool:/var/scalepool
      - ./ConfigDB:/var/ConfigDB
    networks:
      - testnet
  db:
    image: mariadb:${MARIADB_VER}
    container_name: survey_db
    ports:
      - ${SQL_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - testnet

volumes:
  db-data:

networks:
  testnet:
