version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: ${SERVER_NAME}
    ports:
      - ${HTTP_PORT}:80
    links:
      - "db:database"
    restart: always
    volumes:
      - ./server/www:/var/www/html/
  db:
    container_name: ${DB_NAME}
    image: mariadb:${MARIADB_VER}
    ports:
      - ${SQL_PORT}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
